In [1]:
import numpy as np

In [3]:
security_breaches = np.array([[0, 5, 1],
[0, 2, 0],
[1, 1, 2],
[2, 2, 1],
[0, 0, 0]])

In [4]:
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [5]:
security_breaches.sum()

17

In [6]:
security_breaches.sum(axis=0)

array([ 3, 10,  4])

In [7]:
security_breaches.sum(axis=1)

array([6, 2, 4, 5, 0])

In [8]:
security_breaches.min()

0

In [9]:
security_breaches.max()

5

In [10]:
security_breaches.min(axis=1)

array([0, 0, 1, 1, 0])

In [21]:
security_breaches.min(axis=0)

array([0, 0, 0])

In [12]:
security_breaches.mean()

1.1333333333333333

In [13]:
security_breaches.mean(axis=1)

array([2.        , 0.66666667, 1.33333333, 1.66666667, 0.        ])

In [14]:
security_breaches.mean(axis=0)

array([0.6, 2. , 0.8])

In [15]:
security_breaches.sum(axis=1)

array([6, 2, 4, 5, 0])

In [16]:
security_breaches.sum(axis=1, keepdims=True)

array([[6],
       [2],
       [4],
       [5],
       [0]])

In [18]:
security_breaches.sum(axis=0)

array([ 3, 10,  4])

In [19]:
security_breaches.sum(axis=0, keepdims=True)

array([[ 3, 10,  4]])

In [26]:
security_breaches.cumsum(axis=0)

array([[ 0,  5,  1],
       [ 0,  7,  1],
       [ 1,  8,  3],
       [ 3, 10,  4],
       [ 3, 10,  4]])

In [23]:
security_breaches.cumsum(axis=1)

array([[0, 5, 6],
       [0, 2, 2],
       [1, 2, 4],
       [2, 4, 5],
       [0, 0, 0]])

In [27]:
np.arange(1000000).sum()

1783293664

In [28]:
yeah = np.arange(1000000)

In [29]:
yeah

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [30]:
# importing the modules
import numpy as np
import timeit

# vectorized sum
print(np.sum(np.arange(15000)))

print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))

# iterative sum
total = 0
for item in range(0, 15000):
	total += item
a = total
print("\n" + str(a))

print("Time taken by iterative sum : ", end = "")
%timeit a


112492500
Time taken by vectorized sum : 49.8 µs ± 4.31 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

112492500
Time taken by iterative sum : 56.9 ns ± 4.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [31]:
# importing the modules
import numpy as np
import timeit
import math

# vectorized operation
print("Time taken by vectorized operation : ", end = "")
%timeit np.exp(np.arange(150))

# non-vectorized operation
print("Time taken by non-vectorized operation : ", end = "")
%timeit [math.exp(item) for item in range(150)]


Time taken by vectorized operation : 8.16 µs ± 383 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
Time taken by non-vectorized operation : 55 µs ± 1.74 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [35]:
# array = np.array([[1, 2, 3], [4, 5, 6]])
# array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# array + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array_b = np.array([[0, 1, 0], [1, 0, 1]])
array_b

array_a + array_b

In [44]:
#array_a = np.array([[1, 2, 3], [4, 5, 6]])
#array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
#array_b = np.array([[0, 1, 0], [1, 0, 1]])
#array_b

array([[0, 1, 0],
       [1, 0, 1]])

In [46]:
#array_a * array_b

array([[0, 2, 0],
       [4, 0, 6]])

array = np.array([[1, 2, 3], [4, 5, 6]])
array

#array > 2

mask = array > 2
#array[mask]

In [51]:
array = np.array(["NumPy", "is", "awesome"])
array

array(['NumPy', 'is', 'awesome'], dtype='<U7')

In [52]:
len(array) > 2

True

In [54]:
vectorized_len = np.vectorize(len)

In [55]:
vectorized_len = np.vectorize(len)

In [56]:
vectorized_len(array) > 2

array([ True, False,  True])

In [63]:
a = np.array([1, 2, 3])  # Forma: (3,)
a

array([1, 2, 3])

In [65]:
b = np.array([[4], [5], [6]])  # Forma: (3, 1)
b

array([[4],
       [5],
       [6]])

In [68]:
a.ndim

1

In [67]:
a.shape

(3,)

In [59]:
b.ndim

2

In [69]:
b.shape

(3, 1)

In [60]:
a+b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [70]:
c = np.array([[1, 2], [3, 4]])  # Forma: (2, 2)
c

array([[1, 2],
       [3, 4]])

In [71]:
d = np.array([5, 6])  # Forma: (2,)
d

array([5, 6])

In [72]:
c+d

array([[ 6,  8],
       [ 8, 10]])