In [5]:
import numpy as np

In [6]:
a = np.arange(5).reshape(1, 1, 5)
a

array([[[0, 1, 2, 3, 4]]])

In [7]:
a.shape

(1, 1, 5)

In [8]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [9]:
b.shape

(5,)

In [10]:
a + b

array([[[0, 2, 4, 6, 8]]])

In [13]:
a

array([[[0, 1, 2, 3, 4]]])

In [12]:
 1 + a

array([[[1, 2, 3, 4, 5]]])

In [14]:
c = np.arange(6).reshape(2, 3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
c.shape

(2, 3)

In [16]:
d = np.array([[100], [200]])
d

array([[100],
       [200]])

In [17]:
d.shape

(2, 1)

In [18]:
c + d

array([[100, 101, 102],
       [203, 204, 205]])

In [25]:
e = np.array([100, 200, 300])
e

array([100, 200, 300])

In [24]:
e.shape

(3,)

In [23]:
f = np.arange(6).reshape(2, 3)
f

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
f.shape

(2, 3)

In [27]:
e + f

array([[100, 201, 302],
       [103, 204, 305]])

In [32]:
e

array([100, 200, 300])

In [34]:
e_nuevo= e.reshape(1,3)

In [35]:
e_nuevo

array([[100, 200, 300]])

In [36]:
e_final = e_nuevo.reshape(2,3)

ValueError: cannot reshape array of size 3 into shape (2,3)

In [37]:
#a + [1, 2]

ValueError: operands could not be broadcast together with shapes (1,1,5) (2,) 

In [41]:
a

array([[[0, 1, 2, 3, 4]]])

In [44]:
a.shape

(1, 1, 5)

In [42]:
g = np.array([1,2])
g

array([1, 2])

In [45]:
g.shape

(2,)

In [43]:
a + g

ValueError: operands could not be broadcast together with shapes (1,1,5) (2,) 