**Desde una terminal:**

In [ ]:
# pip install numpy


**Desde una celda de código de Jupyter Notebooks:**

In [ ]:
# !pip install numpy

**Para trabajar con Numpy debemos importarla como:**

In [3]:
import numpy as np

In [2]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [3]:
print(a)

42


In [4]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [6]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# Array de cuatro dimensiones
#datos = [[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]]

array_4d = np.array(datos)

print(array_4d)


[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]


In [9]:
# array de tres dimensiones
#data = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
array_3d = np.array(data)

print(array_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Supongamos que tienes una lista de 2D arrays (por ejemplo, 10x10)
lista_arrays = [
    np.random.random((10, 10)),
    np.random.random((10, 10)),
    np.random.random((10, 10))
]

# Convierte la lista en un array 3D
#array_3d = np.dstack(lista_arrays)

print(array_3d.shape)  # Debería ser (10, 10, 3)
print(array_3d)

(10, 10, 3)
[[[0.69500942 0.95296751 0.06961152]
  [0.03757462 0.67799389 0.49133249]
  [0.8054559  0.3850331  0.24561346]
  [0.53352382 0.37672278 0.25995876]
  [0.30592798 0.81924526 0.10621013]
  [0.49252346 0.20964704 0.33487882]
  [0.92863458 0.49902847 0.1009777 ]
  [0.32105971 0.2190574  0.92729943]
  [0.1572389  0.97710787 0.5101201 ]
  [0.61451354 0.24470009 0.18925452]]

 [[0.21963575 0.13506536 0.23800374]
  [0.35016413 0.04482173 0.74752306]
  [0.38587993 0.68780601 0.51131722]
  [0.44806938 0.56592005 0.17353801]
  [0.45576784 0.94069169 0.38180968]
  [0.55603744 0.0089911  0.7185513 ]
  [0.48811996 0.90382159 0.05346098]
  [0.25803249 0.94509662 0.86508115]
  [0.13045919 0.1754257  0.10420507]
  [0.67114866 0.31668489 0.96789682]]

 [[0.31925335 0.69451167 0.7051132 ]
  [0.08112653 0.79234627 0.47222184]
  [0.25362003 0.80616811 0.44311591]
  [0.55964885 0.09179121 0.52591783]
  [0.27673789 0.17394023 0.5380444 ]
  [0.23922299 0.3330898  0.2433177 ]
  [0.08006723 0.584851

In [30]:
#array 5d
data = [[[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]]]

array_5d = np.array(data)
print(array_5d)


[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[13 14 15]
    [16 17 18]]

   [[19 20 21]
    [22 23 24]]]]]


In [32]:
print(array_5d.ndim)

5


In [17]:
# Verificando el numero de dimensiones
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3], [4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
# Construyendo arrays con ndmin
array_5 = np.array([1,2,3,4],ndmin=5 )
print(array_5)

[[[[[1 2 3 4]]]]]


In [21]:
# Construyendo arrays con ndmin
array_a = np.array([1,2,3,4,6,8],ndmin=5 )
print(array_a)

[[[[[1 2 3 4 6 8]]]]]


In [25]:
# Construyendo arrays con ndmin
array_a = np.array([[1,2,3,4,6,8], [9, 10,11, 14, 15, 16]],ndmin=5 )
print(array_a)

[[[[[ 1  2  3  4  6  8]
    [ 9 10 11 14 15 16]]]]]


In [26]:
x = np.array([[[5, 8, 20, 34, 0],
[6, 7, 3, 5, 1],
[7, 80, 4, 36, 2]],
[[5, 7, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 8, 4, 36, 2]],
[[5, 78, 2, 3, 0],
[6, 19, 3, 3, 1],
[7, 8, 4, 36, 24]]])

In [27]:
print(x)

[[[ 5  8 20 34  0]
  [ 6  7  3  5  1]
  [ 7 80  4 36  2]]

 [[ 5  7  2 34  0]
  [ 6 79  3 35  1]
  [ 7  8  4 36  2]]

 [[ 5 78  2  3  0]
  [ 6 19  3  3  1]
  [ 7  8  4 36 24]]]


In [28]:
print(x.ndim)

3


In [39]:
h = np.array([[[1,2],[3,4], [5,6]],[[5,7],[6,8],[9,3]]], ndmin=6)
print(h)

[[[[[[1 2]
     [3 4]
     [5 6]]

    [[5 7]
     [6 8]
     [9 3]]]]]]


In [41]:
array_1_2D = np.array([[1, 2], [5, 7]])
array_2_2D = np.array([[8, 9], [5, 7]])
array_3_2D = np.array([[1, 2], [5, 7]])
array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print(array_1_2D)

[[1 2]
 [5 7]]


In [42]:
print(array_2_2D)

[[8 9]
 [5 7]]


In [43]:
print(array_3_2D)

[[1 2]
 [5 7]]


In [44]:
print(array_3D)

[[[1 2]
  [5 7]]

 [[8 9]
  [5 7]]

 [[1 2]
  [5 7]]]


In [47]:
print(array_3D.ndim)

3


In [4]:
#array_4D = np.array([array_A_3D, array_B_3D, array_C_3D, array_D_3D, array_E_3D,array_F_3D, array_G_3D, array_H_3D, array_I_3D])

In [54]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
print(a1.ndim)

2


In [53]:
a1.shape

(5, 3)

In [55]:
np.random.random((2, 4))

array([[0.77183637, 0.13963875, 0.53352687, 0.39503942],
       [0.2175358 , 0.48649627, 0.57947318, 0.5160233 ]])

In [56]:
np.arange(-3, 4)

array([-3, -2, -1,  0,  1,  2,  3])

In [57]:
np.arange(4)

array([0, 1, 2, 3])

In [58]:
np.arange(-3, 4, 3)

array([-3,  0,  3])

In [59]:
#array = np.zeros((3, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
#array.shape

(3, 5)

In [62]:
array_1 = np.array([[1, 2], [5, 7], [6, 6]])
array_1.ndim

2

In [63]:
print(array_1)

[[1 2]
 [5 7]
 [6 6]]


In [64]:
array_1.flatten()

array([1, 2, 5, 7, 6, 6])

In [65]:
array_1.flatten().ndim

1

In [67]:
array_2 = np.array([[1, 2], [5, 7], [6, 6]])
print(array_2)

[[1 2]
 [5 7]
 [6 6]]


In [69]:
array_2.ndim

2

In [71]:
array_2.shape

(3, 2)

In [74]:
array_2.reshape((3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [75]:
array_2.reshape((2,2))

ValueError: cannot reshape array of size 6 into shape (2,2)

In [80]:
array_2.reshape((2,3)).ndim

2

In [77]:
array_2

array([[1, 2],
       [5, 7],
       [6, 6]])

In [78]:
array_2.reshape(6)

array([1, 2, 5, 7, 6, 6])

In [79]:
array_2.reshape(5)

ValueError: cannot reshape array of size 6 into shape (5,)

In [81]:
x_1 = np.array([[[5, 8, 20, 34, 0],
[6, 7, 3, 5, 1],
[7, 80, 4, 36, 2]],
[[5, 7, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 8, 4, 36, 2]],
[[5, 78, 2, 3, 0],
[6, 19, 3, 3, 1],
[7, 8, 4, 36, 24]]])

In [83]:
x_1.ndim

3

In [84]:
x_1.shape

(3, 3, 5)

In [85]:
x_1

array([[[ 5,  8, 20, 34,  0],
        [ 6,  7,  3,  5,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5,  7,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7,  8,  4, 36,  2]],

       [[ 5, 78,  2,  3,  0],
        [ 6, 19,  3,  3,  1],
        [ 7,  8,  4, 36, 24]]])

In [86]:
array_a = np.array([[1,2,3,4,6,8], [9, 10,11, 14, 15, 16]],ndmin=5 )
print(array_a)

[[[[[ 1  2  3  4  6  8]
    [ 9 10 11 14 15 16]]]]]


In [87]:
array_a.shape

(1, 1, 1, 2, 6)

Indexing

In [89]:
#array = np.array([2, 4, 6, 8, 10])
#array[3]

8

In [90]:
# sudoku_game[2, 4]

NameError: name 'sudoku_game' is not defined

In [91]:
# array = np.array([2, 4, 6, 8, 10])
# array[2:4]

array([6, 8])

In [29]:
import numpy as np

# Crear un array 2D de 9 filas y 9 columnas con valores aleatorios entre 1 y 9
sudoku_array = np.random.randint(1, 10, size=(9, 9))

# Verificar que no haya números repetidos en filas y columnas
for i in range(9):
    if len(set(sudoku_array[i, :])) != 9 or len(set(sudoku_array[:, i])) != 9:
        print("¡El sudoku no cumple las reglas!")
        break
else:
    print("¡Sudoku válido!")

print(sudoku_array)


¡El sudoku no cumple las reglas!
[[1 6 3 8 1 5 1 4 5]
 [6 5 2 4 5 4 4 6 7]
 [8 1 8 1 7 2 6 2 9]
 [9 7 1 2 9 9 4 3 5]
 [8 3 3 8 9 1 7 8 2]
 [9 3 7 9 3 7 5 2 4]
 [3 9 1 9 9 7 4 4 5]
 [7 2 4 9 2 4 7 4 6]
 [3 4 6 8 4 9 5 9 4]]


In [5]:
print(sudoku_array)

[[8 3 5 9 1 1 7 5 9]
 [5 9 6 8 8 7 4 6 8]
 [8 6 7 7 5 9 5 6 2]
 [5 6 1 5 6 2 9 6 7]
 [9 8 8 1 8 4 2 3 8]
 [3 9 5 2 8 4 5 8 9]
 [3 2 8 8 9 7 6 1 1]
 [2 2 9 9 9 5 9 6 6]
 [8 7 1 5 8 1 7 1 3]]


In [6]:
sudoku = sudoku_array

In [8]:
print(sudoku)

[[8 3 5 9 1 1 7 5 9]
 [5 9 6 8 8 7 4 6 8]
 [8 6 7 7 5 9 5 6 2]
 [5 6 1 5 6 2 9 6 7]
 [9 8 8 1 8 4 2 3 8]
 [3 9 5 2 8 4 5 8 9]
 [3 2 8 8 9 7 6 1 1]
 [2 2 9 9 9 5 9 6 6]
 [8 7 1 5 8 1 7 1 3]]


In [9]:
sudoku_game = sudoku


In [10]:
# sudoku_game[2,4]

5

In [11]:
# sudoku_game[0]

array([8, 3, 5, 9, 1, 1, 7, 5, 9])

In [12]:
# sudoku_game[: , 3]

array([9, 8, 7, 5, 1, 2, 8, 9, 5])

# np.array([255], np.uint8) + 1 # 2**8-1 is INT_MAX for uint8
array([0], dtype=uint8)

In [31]:
# np.array([1,2,3]).dtype

dtype('int32')

In [32]:
dtype('int32')

NameError: name 'dtype' is not defined

In [33]:
np.array([255], np.uint8) + 1

array([0], dtype=uint8)

In [34]:
sudoku_game[3:6:2, 3:6:2]

array([[5, 2],
       [2, 4]])

In [35]:
# array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

# print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [36]:
# array_3d.shape


(3, 2, 3)

In [40]:
array_3d = np.array([
    [[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [3, 8, 9, 11, 19, 17], [7, 12, 13, 15, 24, 21]],
    [[13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [4, 9, 10, 12, 21, 18], [8, 13, 14, 16, 25, 22]],
    [[25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36], [5, 10, 11, 13, 22, 19], [9, 14, 15, 17, 26, 23]],
    [[37, 38, 39, 40, 41, 42], [43, 44, 45, 46, 47, 48], [6, 11, 12, 14, 23, 20], [10, 11, 16, 18, 27, 24]]
])

In [41]:
array_3d

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 3,  8,  9, 11, 19, 17],
        [ 7, 12, 13, 15, 24, 21]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [ 4,  9, 10, 12, 21, 18],
        [ 8, 13, 14, 16, 25, 22]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [ 5, 10, 11, 13, 22, 19],
        [ 9, 14, 15, 17, 26, 23]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [ 6, 11, 12, 14, 23, 20],
        [10, 11, 16, 18, 27, 24]]])

1 - ¿Cuál es el elemento en la fila 2, columna 3 y profundidad (capa) 1 del array?

In [42]:
elemento = array_3d[1, 2, 1]
print(f"Elemento en fila 2, columna 3 y profundidad 1: {elemento}")

Elemento en fila 2, columna 3 y profundidad 1: 9


2 - ¿Cuál es el subarray formado por las filas 1 y 2 y las columnas 2 y 3 del array?

In [43]:
submatriz = array_3d[1:3, 1:3]
print(f"Submatriz formada por filas 1 y 2, columnas 2 y 3:\n{submatriz}")

Submatriz formada por filas 1 y 2, columnas 2 y 3:
[[[19 20 21 22 23 24]
  [ 4  9 10 12 21 18]]

 [[31 32 33 34 35 36]
  [ 5 10 11 13 22 19]]]


In [44]:
np.sort(array_3d)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 3,  8,  9, 11, 17, 19],
        [ 7, 12, 13, 15, 21, 24]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [ 4,  9, 10, 12, 18, 21],
        [ 8, 13, 14, 16, 22, 25]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [ 5, 10, 11, 13, 19, 22],
        [ 9, 14, 15, 17, 23, 26]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [ 6, 11, 12, 14, 20, 23],
        [10, 11, 16, 18, 24, 27]]])

In [49]:
np.sort(array_3d, axis=0)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 3,  8,  9, 11, 19, 17],
        [ 7, 11, 13, 15, 24, 21]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [ 4,  9, 10, 12, 21, 18],
        [ 8, 12, 14, 16, 25, 22]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [ 5, 10, 11, 13, 22, 19],
        [ 9, 13, 15, 17, 26, 23]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [ 6, 11, 12, 14, 23, 20],
        [10, 14, 16, 18, 27, 24]]])

In [59]:
# Generate a 2D array with random integers between 0 and 50
array_2d = np.random.randint(0, 51, size=(5, 6))
array_2d  # Print the array contents

array([[29, 26, 13, 18, 15, 30],
       [30,  8, 32, 25, 33, 45],
       [15,  6, 37, 36, 36, 11],
       [ 8, 47, 41,  0, 17, 10],
       [14, 34, 17, 25,  2, 24]])

In [60]:
np.sort(array_2d)

array([[13, 15, 18, 26, 29, 30],
       [ 8, 25, 30, 32, 33, 45],
       [ 6, 11, 15, 36, 36, 37],
       [ 0,  8, 10, 17, 41, 47],
       [ 2, 14, 17, 24, 25, 34]])

In [61]:
np.sort(array_2d, axis=0)

array([[ 8,  6, 13,  0,  2, 10],
       [14,  8, 17, 18, 15, 11],
       [15, 26, 32, 25, 17, 24],
       [29, 34, 37, 25, 33, 30],
       [30, 47, 41, 36, 36, 45]])

In [63]:
np.sort(array_2d, axis=1)

array([[13, 15, 18, 26, 29, 30],
       [ 8, 25, 30, 32, 33, 45],
       [ 6, 11, 15, 36, 36, 37],
       [ 0,  8, 10, 17, 41, 47],
       [ 2, 14, 17, 24, 25, 34]])

In [64]:
array_2d

array([[29, 26, 13, 18, 15, 30],
       [30,  8, 32, 25, 33, 45],
       [15,  6, 37, 36, 36, 11],
       [ 8, 47, 41,  0, 17, 10],
       [14, 34, 17, 25,  2, 24]])

In [5]:
array_3d = np.random.randint(1, 51, size=(2, 3, 3))
array_3d  # Print the array contents

array([[[18, 39, 46],
        [ 1,  4,  6],
        [23,  6,  7]],

       [[21, 37, 11],
        [ 2, 43, 14],
        [ 7, 12,  8]]])

In [6]:
np.sort(array_3d)

array([[[18, 39, 46],
        [ 1,  4,  6],
        [ 6,  7, 23]],

       [[11, 21, 37],
        [ 2, 14, 43],
        [ 7,  8, 12]]])

In [7]:
np.sort(array_3d, axis=0)

array([[[18, 37, 11],
        [ 1,  4,  6],
        [ 7,  6,  7]],

       [[21, 39, 46],
        [ 2, 43, 14],
        [23, 12,  8]]])

In [9]:
array_3d

array([[[18, 39, 46],
        [ 1,  4,  6],
        [23,  6,  7]],

       [[21, 37, 11],
        [ 2, 43, 14],
        [ 7, 12,  8]]])

In [10]:
np.sort(array_3d, axis=0)

array([[[18, 37, 11],
        [ 1,  4,  6],
        [ 7,  6,  7]],

       [[21, 39, 46],
        [ 2, 43, 14],
        [23, 12,  8]]])

In [11]:
np.sort(array_3d, axis=1)

array([[[ 1,  4,  6],
        [18,  6,  7],
        [23, 39, 46]],

       [[ 2, 12,  8],
        [ 7, 37, 11],
        [21, 43, 14]]])

In [13]:
#one_to_five = np.arange(1, 6)
# one_to_five

array([1, 2, 3, 4, 5])

In [16]:
#mask = one_to_five % 2 == 0
#mask

array([False,  True, False,  True, False])

In [17]:
one_to_five = np.arange(1, 6)
mask = one_to_five % 2 == 0
one_to_five[mask]

array([2, 4])

In [18]:
clase_id_edad = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
clase_id_edad

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [19]:
clase_id_edad[:, 1] % 2 == 0

array([ True, False, False,  True])

In [20]:
clase_id_edad[:, 0][clase_id_edad[:, 1] % 2 == 0]

array([1, 4])

In [21]:
clase_id_edad

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [22]:
np.where(clase_id_edad[:, 1] % 2 == 0)

(array([0, 3], dtype=int64),)

In [23]:
np.where(clase_id_edad[:, 0] % 2 == 0)

(array([1, 3], dtype=int64),)

In [ ]:
array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
[0, 0, 5, 0, 0, 9, 0, 0, 1],
[0, 7, 0, 0, 6, 0, 0, 4, 3],
[0, 0, 6, 0, 0, 2, 0, 8, 7],
[1, 9, 0, 0, 0, 7, 4, 0, 0],
[0, 5, 0, 0, 8, 3, 0, 0, 0],
[6, 0, 0, 0, 0, 0, 1, 0, 5],
[0, 0, 3, 5, 0, 8, 6, 9, 0],
[0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [27]:
# Create a 9x9 array of zeros
#sudoku = np.zeros((9, 9), dtype=int)  # Specify integer dtype

# Define the positions where non-zero values should be placed
positions = [(0, 2), (0, 3), (1, 2), (1, 5), (1, 8), (2, 0), (2, 4), (2, 8), (3, 0), (3, 5), (3, 7), (4, 0), (4, 4), (4, 6), (4, 8), (5, 1), (5, 4), (5, 7), (6, 0), (6, 6), (6, 8), (7, 0), (7, 2), (7, 6), (7, 8), (8, 1), (8, 3), (8, 4), (8, 7)]

# Assign non-zero values to the specified positions
for row, col in positions:
    sudoku[row, col] = row * 10

# Print the array
print(sudoku)


[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0 10  0  0 10]
 [20  0  0  0 20  0  0  0 20]
 [30  0  0  0  0 30  0 30  0]
 [40  0  0  0 40  0 40  0 40]
 [ 0 50  0  0 50  0  0 50  0]
 [60  0  0  0  0  0 60  0 60]
 [70  0 70  0  0  0 70  0 70]
 [ 0 80  0 80 80  0  0 80  0]]


In [28]:
#sudoku

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 10,  0,  0, 10,  0,  0, 10],
       [20,  0,  0,  0, 20,  0,  0,  0, 20],
       [30,  0,  0,  0,  0, 30,  0, 30,  0],
       [40,  0,  0,  0, 40,  0, 40,  0, 40],
       [ 0, 50,  0,  0, 50,  0,  0, 50,  0],
       [60,  0,  0,  0,  0,  0, 60,  0, 60],
       [70,  0, 70,  0,  0,  0, 70,  0, 70],
       [ 0, 80,  0, 80, 80,  0,  0, 80,  0]])

In [30]:
#row_ind, column_ind = np.where(sudoku == 0)
#row_ind, column_ind

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3,
        3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        7, 7, 7, 7, 7, 8, 8, 8, 8, 8], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 3, 4, 6, 7, 1, 2, 3, 5, 6, 7, 1,
        2, 3, 4, 6, 8, 1, 2, 3, 5, 7, 0, 2, 3, 5, 6, 8, 1, 2, 3, 4, 5, 7,
        1, 3, 4, 5, 7, 0, 2, 5, 6, 8], dtype=int64))

In [31]:
sudoku= np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
[0, 0, 5, 0, 0, 9, 0, 0, 1],
[0, 7, 0, 0, 6, 0, 0, 4, 3],
[0, 0, 6, 0, 0, 2, 0, 8, 7],
[1, 9, 0, 0, 0, 7, 4, 0, 0],
[0, 5, 0, 0, 8, 3, 0, 0, 0],
[6, 0, 0, 0, 0, 0, 1, 0, 5],
[0, 0, 3, 5, 0, 8, 6, 9, 0],
[0, 4, 2, 9, 1, 0, 3, 0, 0]])
sudoku

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [32]:
sudoku

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [34]:
row_ind, column_ind = np.where(sudoku == 0)
row_ind, column_ind

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8], dtype=int64))

In [35]:
array_2 = np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
[0, 0, 5, 0, 0, 9, 0, 0, 1],
[0, 7, 0, 0, 6, 0, 0, 4, 3],
[0, 0, 6, 0, 0, 2, 0, 8, 7],
[1, 9, 0, 0, 0, 7, 4, 0, 0],
[0, 5, 0, 0, 8, 3, 0, 0, 0],
[6, 0, 0, 0, 0, 0, 1, 0, 5],
[0, 0, 3, 5, 0, 8, 6, 9, 0],
[0, 4, 2, 9, 1, 0, 3, 0, 0]])
array_2

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [36]:
row_ind, column_ind = np.where(array_2 == 0)
row_ind, column_ind

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8], dtype=int64))

In [37]:
row_ind

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
       8, 8], dtype=int64)

In [38]:
column_ind

array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
       3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
       7, 8], dtype=int64)

In [39]:
np.where(array_2 == 0, "", array_2)

array([['', '', '4', '3', '', '', '2', '', '9'],
       ['', '', '5', '', '', '9', '', '', '1'],
       ['', '7', '', '', '6', '', '', '4', '3'],
       ['', '', '6', '', '', '2', '', '8', '7'],
       ['1', '9', '', '', '', '7', '4', '', ''],
       ['', '5', '', '', '8', '3', '', '', ''],
       ['6', '', '', '', '', '', '1', '', '5'],
       ['', '', '3', '5', '', '8', '6', '9', ''],
       ['', '4', '2', '9', '1', '', '3', '', '']], dtype='<U11')

In [40]:
array_2

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

NameError: name 'array_3' is not defined

In [42]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
new_classrooms = np.array([[5, 30], [5, 17]])
np.concatenate((classroom_ids_and_sizes, new_classrooms))

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 5, 17]])

In [43]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
grade_levels_and_teachers = np.array([[1, "James"], [1, "George"], [3,"Amy"],
[3, "Meehir"]])
np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U11')

In [44]:
data_clases = np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

In [45]:
data_clases

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U11')

In [46]:
np.delete(data_clases, 1, axis=0)

array([['1', '22', '1', 'James'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U11')

In [47]:
data_clases

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U11')

In [48]:
np.delete(data_clases, 1, axis=1)

array([['1', '1', 'James'],
       ['2', '1', 'George'],
       ['3', '3', 'Amy'],
       ['4', '3', 'Meehir']], dtype='<U11')

In [49]:
np.delete(data_clases, 1)

array(['1', '1', 'James', '2', '21', '1', 'George', '3', '27', '3', 'Amy',
       '4', '26', '3', 'Meehir'], dtype='<U11')

In [50]:
!pip install astropy

   ---------------------------------------- 0.0/6.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.4 MB 660.6 kB/s eta 0:00:10
   -- ------------------------------------- 0.4/6.4 MB 5.8 MB/s eta 0:00:02
   ---------- ----------------------------- 1.6/6.4 MB 13.0 MB/s eta 0:00:01
   ------------- -------------------------- 2.1/6.4 MB 14.8 MB/s eta 0:00:01
   ----------------- ---------------------- 2.8/6.4 MB 13.7 MB/s eta 0:00:01
   ----------------------- ---------------- 3.7/6.4 MB 14.1 MB/s eta 0:00:01
   -------------------------- ------------- 4.2/6.4 MB 15.8 MB/s eta 0:00:01
   -------------------------------- ------- 5.2/6.4 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------  6.4/6.4 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 6.4/6.4 MB 15.7 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ------------------------- -------------- 1.2/1.9 MB 25.9 MB/s eta 0:00:01
   ------------

In [51]:
from astropy.time import Time

In [53]:
(Time('2017-01-01') - Time('2016-12-31 23:59')).sec

61.00000000001593